---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- name: Include install mongo
  include_tasks: install_mongo.yml
- name: Include config mongo
  include_tasks: config_mongo.yml
