- name: Deploy App
  hosts: appserver
  become: true
  tasks:
    - name: Git install
      apt:
        name: git
        state: present

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: "/home/{{ deploy_user }}/reddit"
        version: monolith
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: "/home/{{ deploy_user }}/reddit"

  handlers:
    - name: reload puma
      systemd:
        name: puma
        state: restarted
